# Generated by Django 5.1.1 on 2024-09-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord', models.CharField(max_length=42)),
                ('tenant', models.CharField(max_length=42)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_address', models.CharField(blank=True, max_length=42)),
            ],
        ),
    ]
