# Generated by Django 5.1.1 on 2024-10-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos_inteligentes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalcontract",
            name="simulated_time",
            field=models.DateField(blank=True, null=True),
        ),
    ]
