# Generated by Django 5.1.1 on 2024-09-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_inteligentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rentalcontract',
            table='contratos',
        ),
    ]
