# Generated by Django 5.1.1 on 2024-10-12 02:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos_inteligentes", "0002_rentalcontract_simulated_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentalcontract",
            name="termination_fee",
        ),
        migrations.AlterField(
            model_name="rentalcontract",
            name="simulated_time",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
