# Generated by Django 5.1.1 on 2024-10-01 00:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_inteligentes', '0003_rentalcontract_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTermination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('terminated_by', models.CharField(max_length=42)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contratos_inteligentes.rentalcontract')),
            ],
            options={
                'db_table': 'encerramento_contratos',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('rent', 'Aluguel'), ('deposit', 'Depósito')], max_length=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contratos_inteligentes.rentalcontract')),
            ],
            options={
                'db_table': 'pagamento_contratos',
            },
        ),
    ]
