# Generated by Django 5.1.1 on 2024-10-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_inteligentes', '0004_rentalcontract_rent_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcontract',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('terminated', 'Terminated')], default='pending', max_length=10),
        ),
    ]
