# Generated by Django 5.1.1 on 2024-10-01 00:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_inteligentes', '0004_contracttermination_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='contracttermination',
            table='encerramento_contrato',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='pagamento_contrato',
        ),
    ]
