# Generated by Django 5.1.1 on 2024-10-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_inteligentes', '0005_payment_paid_at_alter_contracttermination_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcontract',
            name='contract_address',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
